# Start from the base image
FROM node:10
# set the work directory
WORKDIR /usr/src/app
# Copy the file package*.json from your host to your current location
COPY package*.json ./
# RUN npm install command for angular dependencies inside your image filesystem
RUN npm install
# Bundle app source
COPY . .
# Inform Docker that the container is listening on the specified port at runtime.
EXPOSE 4200
# Run the specified command within the container.
ENTRYPOINT ["npm", "start"]
